apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-logging-pv0
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/usr"